version: '3.7'
services:
  API:
    image: 'film2night'
    ports:
      - "8081:8081"
    depends_on:
      PostgreSQL:
        condition: service_healthy

  PostgreSQL:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=film2night
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/F2n_db_tables.sql:/docker-entrypoint-initdb.d/F2n_db_tables.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U f2n_admin -d film2night" ]
      interval: 5s
      retries: 2

  WEB:
    image: tomcat
    ports:
      - "8080:8080"
    volumes:
      - ./target/film2night.war:/usr/local/tomcat/webapps/film2night.war
      - ./target/film2night:/usr/local/tomcat/webapps/ROOT
