version: '3.7'
services:
  API:
    image: 'film2night'
    ports:
      - "8081:8081"
    volumes:
      - ./.env:/usr/local/lib/env
    depends_on:
      PostgreSQL:
        condition: service_healthy

  WEB:
    image: tomcat:10.1.9
    ports:
      - "8080:8080"
    volumes:
      - ./.env:/usr/local/tomcat/webapps/env
      - ./target/film2night.war:/usr/local/tomcat/webapps/film2night.war
      - ./target/film2night:/usr/local/tomcat/webapps/ROOT
    depends_on:
      PostgreSQL:
        condition: service_healthy

  PostgreSQL:
    image: postgres:12.15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${PSQL_PWD}
      - POSTGRES_USER=${PSQL_USER}
      - POSTGRES_DB=${PSQL_F2N_DB}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/F2n_db_tables.sql:/docker-entrypoint-initdb.d/F2n_db_tables.sql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${PSQL_F2N_USER} -d ${PSQL_F2N_DB}"
        ]
      interval: 5s
      retries: 2
