version: '3.7'
services:
  WEB:
    image: tomcat:10.1.9
    container_name: tomcat_web
    ports:
      - "8080:8080"
    volumes:
      - ./.env:/usr/local/env
      - ./target/film2night.war:/usr/local/tomcat/webapps/film2night.war
      - ./target/film2night:/usr/local/tomcat/webapps/ROOT
    depends_on:
      PostgreSQL:
        condition: service_healthy

  PostgreSQL:
    image: postgres:12
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${PSQL_PWD}
      - POSTGRES_USER=${PSQL_USER}
      - POSTGRES_DB=${PSQL_DB}
    volumes:
      - ./.env:/usr/local/env
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/F2n_db_tables.sql:/home/F2n_db_tables.sql
      - ./sql/F2n_dbs.sh:/docker-entrypoint-initdb.d/F2n_dbs.sh
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${PSQL_F2N_USER} -d ${PSQL_F2N_DB}"
        ]
      interval: 5s
      retries: 2
