name: F2N film service CI

on:
  push:
    branches: [ "main", "develop" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml

    - name: 'Create env file'
      run: |
        echo "${{secrets.ENV_FILE}}" > .env
  
    - name: 'Create env.test file'
      run: |
        echo "${{secrets.TEST_ENV_FILE}}" > .env.test
  
    - name: Docker compose
      run: docker-compose up -d
  
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v4.0.0
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        JACOCO_SOURCE_PATH: "${{github.workspace}}/src/main/java"
      with:
        coverageCommand: mvn test
        coverageLocations: ${{github.workspace}}/target/site/jacoco/jacoco.xml:jacoco
